import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-slate-400">
          <h1>Header</h1>
        </div>
        {children}
        <div className=" bg-slate-400">
          <h1>Fotter</h1>
        </div>
      </body>
    </html>
  );
}
